### ISSUE TITLE
not detecting resources

### ISSUE THREAD

**Issue by shifoc** [harsilspatel/moodle-downloader#20]
The extension is not detecting any resource files

**Comment by harsilspatel** [comment]
Hi @ssccc,

Thanks for reporting the issue. I just tried it on the moodle demo [site](https://school.moodledemo.net/) and the resources tab seems to be working fine. Would you mind providing me with the console output? Here's how you can go about retrieving the extension's logs:

![Kapture 2020-03-06 at 6 51 02](https://user-images.githubusercontent.com/25992839/76020278-34cfc500-5f77-11ea-945d-cd63570405e5.gif)

**Comment by shifoc** [comment]
hello @harsilspatel , the site for my moodle is https://lms.aub.edu.lb/ below is a screenshot of the console you requested
![image](https://user-images.githubusercontent.com/32818143/76708062-b1dc0680-66fc-11ea-822d-8c656b1ce81d.png)

**Comment by harsilspatel** [comment]
Hi @ssccc,

Thanks for taking the time to provide the logs. The latest release should fix the issue. Additionally, I discovered (and fixed) a bug which prevented the files from organizing in a directory structure!

So thank you for raising the issue. And please do not hesitate to re-open this issue or create a new one if you any other bugs. :)

Regards,
Harsil

**Comment by shifoc** [comment]
Hello, it was working fine after you fixed it but since the last update the same problem happened again. @harsilspatel 

![image](https://user-images.githubusercontent.com/32818143/78385034-e2b8a880-75e3-11ea-887e-223135e430f4.png)

**Comment by harsilspatel** [comment]
Hi @ssccc,

That definitely not the expected behaviour. I can't reproduce the issue on the Moodle demo [site](https://school.moodledemo.net/mod/page/view.php?id=46). However, I've just updated the extension to v1.5.1, do you mind giving that a shot and see if that fixes things?

**Comment by shifoc** [comment]
it's still happening

**Comment by harsilspatel** [comment]
As you may have noticed, I've rolled back to an older version till I find a fix. I might need help to test it out since I cannot reproduce the issues on my end, would you be interested to help out?

**Comment by shifoc** [comment]
@harsilspatel of course I am happy to help

**Comment by shifoc** [comment]
hello, @harsilspatel it happened again

**Comment by shifoc** [comment]
![image](https://user-images.githubusercontent.com/32818143/115966063-b2b4ae00-a534-11eb-82d7-d7574007f5a1.png)

**Comment by harsilspatel** [comment]
Hi @shifoc,

Do you mind trying out the latest `master` branch that should fix it! It should be published in the Chrome Web store in a day or two but until then you can clone the repo.

If not please feel free to reopen this issue and I'd be happy to have a look :)

Regards,
H

**Comment by shifoc** [comment]
![image](https://user-images.githubusercontent.com/32818143/116559461-2aa22000-a909-11eb-9ee1-c3a7fcc2b7a2.png)
hey, there is still an error.
